{ config, lib, pkgs, ... }:

#
# This file exists as a turnkey example and can be replaced with autogenerated
# equivalent from nixos-install
#

{
  fileSystems."/" =
    { device = "/dev/disk/by-label/root";
    };
}
